# Generated by Django 2.0.1 on 2018-02-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.IntegerField(unique=True)),
                ('content', models.CharField(blank=True, max_length=1000, null=True)),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
            ],
        ),
    ]
