# Generated by Django 2.0.1 on 2018-02-01 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='owner',
        ),
    ]
